name: deploy-website

# Only run this when the master branch changes
on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
        uv pip install --system -r execute-requirements.txt

    # Build the book
    - name: Build the site
      run: |
        myst build --html

    # Move RSS feeds to output folder
    # - name: Move RSS feeds
    #   run: |
    #     cp atom.xml _build/html/atom.xml
    #     cp rss.xml _build/html/rss.xml

    # If we've pushed to main, push the book's HTML to github-pages
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html